spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: null
    platform: h2
    hikari:
      connection-test-query: SELECT 1
jpa:
  database: H2
  show-sql: true
  generated-ddl: true
  hibernate:
    ddl-auto: validate
flyway:
  baseline-on-migrate: true
  validate-on-migration: true
